### ISSUE TITLE
[BE] OAuth 기능개선

### ISSUE THREAD

**Issue by Malloc72P** [kjk402/issue-tracker#17]
- [x] ClientID와 CallbackURL(Scheme포함)을 제공하는 API 구현
- [x] 로그인 기능 관련 잔 버그 수정
- [x] 나중에 하게 될 Apple  OAuth를 대비한 리팩토링

**Comment by Malloc72P** [comment]
@Malloc72P

**Comment by ppamppamman** [comment]
안녕하세요 FE 빰빰입니다. 시간이 새벽인지라 슬랙알람이 울리지 않을까 걱정이 되어서 이슈가 열려있는 김에 댓글로 여쭙니다.
그 지난번에 이야기 했다가 FE가 일찍 클래스모임이 시작되는 바람에 이야기를 못나눴던 것을 여쭤보려구요!

현재 OAuth의 콜백url이 client의 URL인 현재의 localhost로 안되어있구 백엔드의 URL로 잡혀있다는 것을 말씀드렸었습니다.
이것으로부터 발생하는 문제는 깃헙 로그인 절차가 진행된 후 다시 클라이언트 사이드로 리다이렉트가 되지 않아 리액트를 통해 후속 절차를 진행할 수 없다(code를 백엔드에 보내서 유저리소스를 실제 확인하고 회원가입 절차를 진행하는 행동)는 것입니다.

제 판단에는 github으로부터의 code를 클라이언트사이드의 앱이 받아 백엔드에 넘기고 이것으로부터 실제 유저리소스를 조회해야하는 것이 맞는 흐름이지 않나 생각됩니다. 그래서 간단하게 스스로 백엔드 서버를 만들어서 절차를 처리해 보니까 일단 제 생각대로 처리는 되었습니다.
다만 금요일에 나스께서 그 "이전 로그인 작업도 이 흐름으로 진행했다." 라고 말씀하셨어서요. 혹시 제가 나스가 하셨던 OAuth의 흐름으로 작업된 FE의 프로젝트를 참고해 볼 수 있을까요? 어떤걸 좀 보면 좋으려나요? @Malloc72P

**Comment by Malloc72P** [comment]
> 안녕하세요 FE 빰빰입니다. 시간이 새벽인지라 슬랙알람이 울리지 않을까 걱정이 되어서 이슈가 열려있는 김에 댓글로 여쭙니다.
> 그 지난번에 이야기 했다가 FE가 일찍 클래스모임이 시작되는 바람에 이야기를 못나눴던 것을 여쭤보려구요!
> 
> 현재 OAuth의 콜백url이 client의 URL인 현재의 localhost로 안되어있구 백엔드의 URL로 잡혀있다는 것을 말씀드렸었습니다.
> 이것으로부터 발생하는 문제는 깃헙 로그인 절차가 진행된 후 다시 클라이언트 사이드로 리다이렉트가 되지 않아 리액트를 통해 후속 절차를 진행할 수 없다(code를 백엔드에 보내서 유저리소스를 실제 확인하고 회원가입 절차를 진행하는 행동)는 것입니다.
> 
> 제 판단에는 github으로부터의 code를 클라이언트사이드의 앱이 받아 백엔드에 넘기고 이것으로부터 실제 유저리소스를 조회해야하는 것이 맞는 흐름이지 않나 생각됩니다. 그래서 간단하게 스스로 백엔드 서버를 만들어서 절차를 처리해 보니까 일단 제 생각대로 처리는 되었습니다.
> 다만 금요일에 나스께서 그 "이전 로그인 작업도 이 흐름으로 진행했다." 라고 말씀하셨어서요. 혹시 제가 나스가 하셨던 OAuth의 흐름으로 작업된 FE의 프로젝트를 참고해 볼 수 있을까요? 어떤걸 좀 보면 좋으려나요? @Malloc72P

저도 좀 더 찾아봤는데요, 빰빰 말대로 하는게 맞는것 같아요. 
저번에 말씀하신대로 콜백url 수정하도록 하겠습니다
@ppamppamman

**Comment by ppamppamman** [comment]
> > 안녕하세요 FE 빰빰입니다. 시간이 새벽인지라 슬랙알람이 울리지 않을까 걱정이 되어서 이슈가 열려있는 김에 댓글로 여쭙니다.
> > 그 지난번에 이야기 했다가 FE가 일찍 클래스모임이 시작되는 바람에 이야기를 못나눴던 것을 여쭤보려구요!
> > 현재 OAuth의 콜백url이 client의 URL인 현재의 localhost로 안되어있구 백엔드의 URL로 잡혀있다는 것을 말씀드렸었습니다.
> > 이것으로부터 발생하는 문제는 깃헙 로그인 절차가 진행된 후 다시 클라이언트 사이드로 리다이렉트가 되지 않아 리액트를 통해 후속 절차를 진행할 수 없다(code를 백엔드에 보내서 유저리소스를 실제 확인하고 회원가입 절차를 진행하는 행동)는 것입니다.
> > 제 판단에는 github으로부터의 code를 클라이언트사이드의 앱이 받아 백엔드에 넘기고 이것으로부터 실제 유저리소스를 조회해야하는 것이 맞는 흐름이지 않나 생각됩니다. 그래서 간단하게 스스로 백엔드 서버를 만들어서 절차를 처리해 보니까 일단 제 생각대로 처리는 되었습니다.
> > 다만 금요일에 나스께서 그 "이전 로그인 작업도 이 흐름으로 진행했다." 라고 말씀하셨어서요. 혹시 제가 나스가 하셨던 OAuth의 흐름으로 작업된 FE의 프로젝트를 참고해 볼 수 있을까요? 어떤걸 좀 보면 좋으려나요? @Malloc72P
> 
> 저도 좀 더 찾아봤는데요, 빰빰 말대로 하는게 맞는것 같아요.
> 저번에 말씀하신대로 콜백url 수정하도록 하겠습니다
> @ppamppamman

아이고 주말 새벽에 죄송합니다ㅠㅠ 천천히 확인하셨으면 했어서 댓글을 남긴것이었는데 벌써 피드백이 이뤄졌군요
감사합니다감사합니다

**Comment by Malloc72P** [comment]
선생님 빨리 주무십쇼 ㅎㅎ
